# Generated by Django 5.1 on 2024-08-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default='No directions added yet for this recipe', max_length=500),
        ),
    ]
